image: Visual Studio 2015
version: "{build}"
platform: x64

test: off
deploy: off

install:
  - ps: Install-Product node 4

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))
